jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-jammy
      options: --user=root
    env:
      HOME: /root
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      DOCKER_CONFIG: /tmp/.docker   # ← évite /root/.docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false
          lfs: false

      - name: Silence Docker warning
        run: |
          mkdir -p "$DOCKER_CONFIG"
          echo '{}' > "$DOCKER_CONFIG/config.json"

      - name: Cache npm (~/.npm)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Run Playwright (HTML)
        run: |
          [ -f .env.ci ] && cp .env.ci .env
          npm ci --no-audit --no-fund --prefer-offline
          npx playwright test -c ci.config.ts --reporter=html
