name: Playwright (cached, HOME=/root)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-jammy
      options: --user=root            # s'assure que /root est accessible
    env:
      HOME: /root                     # workaround
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"   # navigateurs déjà dans l'image
    steps:
      - uses: actions/checkout@v4

      - name: Cache npm (~/.npm)
        uses: actions/cache@v4
        with:
          path: ~/.npm                # => /root/.npm grâce à HOME=/root
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install + Test
        shell: bash
        run: |
          [ -f .env.ci ] && cp .env.ci .env
          npm ci --no-audit --no-fund --prefer-offline
          npx playwright test -c ci.config.ts
