name: Playwright (cached)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.56.0-jammy
    steps:
      - uses: actions/checkout@v4

      # Cache du cache npm (~/.npm), idéal avec "npm ci"
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install + Test
        shell: bash
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"  # navigateurs déjà dans l'image
          WORKDIR: "."                           # change si tes tests sont ailleurs
        run: |
          set -euo pipefail
          cd "$WORKDIR"
          [ -f .env.ci ] && cp .env.ci .env
          npm ci --no-audit --no-fund --prefer-offline
          npx playwright test -c ci.config.ts
